version: "3"
services:
  metabase:
    image: metabase/metabase:v0.35.3
    container_name: homevis_metabase
    restart: on-failure:5
    depends_on:
      - metabase_db
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${METABASE_DB}
      MB_DB_PORT: 5432
      MB_DB_USER: ${METABASE_USER}
      MB_DB_PASS: ${METABASE_PASSWORD}
      MB_DB_HOST: homevis_metabase_db

  metabase_db:
    image: postgres:12.2-alpine
    container_name: homevis_metabase_db
    restart: on-failure:5
    volumes:
      - metabase_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${METABASE_DB}
      POSTGRES_USER: ${METABASE_USER}
      POSTGRES_PASSWORD: ${METABASE_PASSWORD}

  db:
    image: postgres:12.2-alpine
    container_name: homevis_db
    restart: on-failure:5
    volumes:
      - homevis_db_data:/var/lib/postgresql/data
      - ./db/src/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${HOMEVIS_DB}
      POSTGRES_USER: ${HOMEVIS_USER}
      POSTGRES_PASSWORD: ${HOMEVIS_PASSWORD}

  cron:
    build: ./cron
    container_name: homevis_cron
    restart: on-failure:5
    environment:
      TEPCO_USERNAME: ${TEPCO_USERNAME}
      TEPCO_PASSWORD: ${TEPCO_PASSWORD}
      POSTGRES_DB: ${HOMEVIS_DB}
      POSTGRES_USER: ${HOMEVIS_USER}
      POSTGRES_PASSWORD: ${HOMEVIS_PASSWORD}

  smtp:
    image: tecnativa/postfix-relay
    container_name: homevis_smtp
    restart: on-failure:5
    environment:
      MAIL_RELAY_HOST: smtp.gmail.com
      MAIL_RELAY_PORT: 587
      MAIL_RELAY_USER: ${SMTP_USERNAME}
      MAIL_RELAY_PASS: ${SMTP_PASSWORD}



volumes:
  homevis_db_data:
  metabase_db_data:
